version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: 'pet_adoption'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'local'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  backend:
    build: ./pet-adoption-api
    container_name: backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pet_adoption
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: local
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build: ./pet-adoption-front
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: on-failure
